In [1]:
import joblib

model = joblib.load("../models/batsman_runs_model.pkl")
pipeline = joblib.load("../models/featurepipeline.pkl")

print(model)
print(pipeline)

RandomForestRegressor(random_state=42)
Pipeline(steps=[('scaler', StandardScaler())])

In [3]:
import pandas as pd
import joblib

# Load model & pipeline
model = joblib.load("../models/batsman_runs_model.pkl")
pipeline = joblib.load("../models/featurepipeline.pkl")

# Load new match features
new_data = pd.read_csv("../data/new_match_features.csv")
new_data.head()

,avg_runs_last_5,venue_avg_runs,opponent_avg_runs,career_avg_runs,matches_played,strike_rate
0,32.5,35.2,30.1,34.8,120,138.5
1,45.1,42.0,40.3,41.6,80,145.2

In [4]:
new_data_processed = pipeline.transform(new_data)
predicted_runs = model.predict(new_data_processed)

new_data["predicted_runs"] = predicted_runs
new_data

c:\Users\Anisha\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

,avg_runs_last_5,venue_avg_runs,opponent_avg_runs,career_avg_runs,matches_played,strike_rate,predicted_runs
0,32.5,35.2,30.1,34.8,120,138.5,6.235000
1,45.1,42.0,40.3,41.6,80,145.2,5.983333

In [5]:
new_data.to_csv("../data/predicted_runs_output.csv", index=False)